# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'card-detector-tflite' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'TensorFlowLiteSwift'
  # Pods for card-detector-tflite

end
